import type { Metadata } from "next";
import { ThemeProvider } from "./providers/ThemeProvider";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { ImageProvider } from "./providers/ImageProvider";
import { FilterProvider } from "./providers/operationProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ImageProvider>
            <Navbar />
            <FilterProvider>{children}</FilterProvider>
          </ImageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
